### ISSUE TITLE
Lint this package

### ISSUE THREAD

**Issue by israellevin** [paket-core/router#10]
The current working commit (69170bfcf10eb0dc0b9d146325bdf84973768177) has pycodestyle and pylint issues. Please fix.

**Comment by yaroslavr-itd** [comment]
`too-many-branches` fixed in:
- [9978943](https://github.com/paket-core/router/commit/99789430556381839a30c09a36dc1b5220934c61)
- [16c3c01](https://github.com/paket-core/router/commit/16c3c01c70b7f5d69df3180518b3aae1e8fdf80e)
- [54b8840](https://github.com/paket-core/router/commit/54b88402857e897ef9300d1666602dd213a58a2f)

`too-many-locals` fixed in:
- [22fa2dc8](https://github.com/paket-core/router/commit/22fa2dc87de89f3539ac0374d213ee3743cb7ee1)

tests fixed in:
- [c45d765](https://github.com/paket-core/router/commit/c45d765cbde4af4383333d1c4a46ae051ef08376)
